name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
    
      - name: Get dependencies
        run: flutter pub get
    
      - name: Build release project
        run: flutter build web --base-href=/ 

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build/web
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "tiagorodriguessousa9@gmail.com"
          git config --global user.name "Tiago Rodrigues Sousa"
          cd build
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://${{ secrets.TOKEN }}@github.com/tiagors09/tiagors09.github.io.git" master:gh-pages
